language: go
go:
- '1.8'
sudo: required
services:
- docker

before_install:
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -

install:
  make vendor

script:
- make build
- make darwin
- make freebsd

before_deploy:
- mkdir -p bin_release
- CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -a -ldflags "-extldflags '-static' -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-iscsi-provisioner_linux-amd64
- CGO_ENABLED=0 GOOS=darwin  GOARCH=amd64 go build -a -ldflags "-extldflags '-static' -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-iscsi-provisioner_darwin-amd64
- CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -a -ldflags "-extldflags '-static' -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-iscsi-provisioner_freebsd-amd64

deploy:
- provider: script
  script: bash .travis/docker-release.sh
  skip_cleanup: true
  on:
    repo: travisghansen/freenas-iscsi-provisioner
    branch: "master"

- provider: script
  script: bash .travis/docker-release.sh
  skip_cleanup: true
  on:
    repo: travisghansen/freenas-iscsi-provisioner
    tags: true

- provider: releases
  api_key:
    secure: gh6irydkkZ5Q+BTfYJ9+554IfNalaCsSEAEUkcFRf8mCQltttApo7lQtoOIQFZrQhxkfJukhZBogdDJ1cYb/KJD0j5+XZx7dSHXYHqYy03KYZbWdHvhaBENDM5sxZG1QSfva9pP6x8XQDn3/5p8amUuWwCtlAWrKfh+tfdkyaeBWppzP1xxoeee4DekBaGNWSmN/+Ebvw+4XkrJDi2KnufkiWiUg4JdBIPJNWJXzXUVC2TIa7915iGFQ0wNcJHd50kXncCjFGUufBDauxa1U72jdAByy6e+yHlWXB1h0jw15UD89i+YMCHx+oJo94+DiJh/J+5RR4sEx6+Nqo8tH4CBW2C83RdMMRAy6/sUXtlFEpPRoyUXfLxIvxuNco5DdKb2Z2P+fuJFsNWVKWN/htKXtLxWD1SxjpldfmfieKhGB4xB+hJAvNRq7K4kd5IRCX9O9IWvcuy2+uybovraDqPk6oWpPCiC6wThXt5ELw48ga9WwRbtuMt+bX0jFqzQMeS8Xgcwu0WZ+VDLqixr+NPGrt+lVTvEYUADRRpT1B25N/Ssmtxut+Tk2D2U9qJ6leYzBp8KcavliG72qt/6fdi6bQ9l4rlupq2CwNaqEJW+1WyAHi759138RacVRJwIX6oi1YvYqSR7jCFhc4H7IxxPjvUPDaQmzXAfsZmgESXY= 
  file_glob: true
  file: bin_release/*
  skip_cleanup: true
  on:
    tags: true
  go: 1.8
