language: go
go:
- '1.12'
sudo: required
services:
- docker

before_install:
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.13.3 && go install && cd -

install:
  make vendor

script:
- mkdir -p bin_release
- CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -a -ldflags "-extldflags '-static' -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-iscsi-provisioner_linux-amd64
- CGO_ENABLED=0 GOOS=darwin  GOARCH=amd64 go build -a -ldflags "-extldflags '-static' -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-iscsi-provisioner_darwin-amd64
- CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -a -ldflags "-extldflags '-static' -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-iscsi-provisioner_freebsd-amd64

deploy:
- provider: script
  script: bash .travis/docker-release.sh
  skip_cleanup: true
  on:
    repo: travisghansen/freenas-iscsi-provisioner
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|next$

- provider: script
  script: bash .travis/docker-release.sh
  skip_cleanup: true
  on:
    repo: travisghansen/freenas-iscsi-provisioner
    tags: true

- provider: releases
  api_key:
    secure: vwSFzauTyovyCvHcgbBLIQld8sRxKgh2jpegR01Mf6Oz3sMLhcVKCT/EUrvV/0zAotGGFnOfCd1eGEtEpa+VzrA1Zp+c/iw+qY2cW4uM9ocMYIjnDcoA+UQP4OJLX7D6jF0GPxvfPOm3DTEKn8psyV7XRHCUM4uMZ7HlXaautYFtWYwE7epLdr4W9ksU43I1xiBNbX71dnLLosqXtayu91BSHL5NIKMokQiA5IVQ0qA7PTB4bJ2qniYic/XjdFdpE8j6e2M0BkRy8p1hS724W4IkBvhFgVpogk/xSPMUw0fFHqPDF1x9VLR+8t4MvbrtFYfXsmKnrzcroxaooGeBdGGudg1hQG5D5T+s5OVHJFi5KpmHdcaEP/vgEue0HEwmmKgAKb/j8tOIwMUqOmo8Iaa/dkccqOsv162vVogDQhUaePcrvrnW5TAuDZ3ikJEWDCw+OlpUgKztGPedVpViQ5eHgflM+0475jWNULzzR2LGk+aSqjxC/vZAnFfk3bC6yav3iV1vMz1wykKreQNS08drz8v+0g8IK4TMTPCdalEMejRZgMALOAB/Nbk+IoSioU3tRaJzISGlIxTnwf0JeNr60CXevwxmXHyQrKBHhNRVLLM3v5nOOm/rWTtQS8liHM8mM/Y6HfpBr1gg5OJxazGtluQDa8todZvZYQ++4gc=
  file_glob: true
  file: bin_release/*
  skip_cleanup: true
  on:
    tags: true
  go: 1.12
